### ISSUE TITLE
Does not build with latest GCC (6.2.1)

### ISSUE THREAD

**Issue by m4ng0squ4sh** [logrotate/logrotate#60]
logrotate package does not build from source with latest gcc (6.2.1): gcc complains about the indentation of postrotateSingleLog() in [logrotate.c](https://github.com/logrotate/logrotate/blob/8ba7323ce4867873bed1fc5e8b6ecee5c718a891/logrotate.c#L1788-L1804 ).

```
logrotate.c: In function ‘postrotateSingleLog’:
logrotate.c:1784:5: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
     if (!state->doRotate)
     ^~
logrotate.c:1787:2: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
  if (!hasErrors && log->flags & LOG_FLAG_TMPFILENAME) {
  ^~
mv -f .deps/config.Tpo .deps/config.Po
cc1: all warnings being treated as errors
make[1]: *** [Makefile:413: logrotate.o] Error 1
make[1]: Leaving directory '/tmp/build/logrotate/src/logrotate-3.9.2'
make: *** [Makefile:433: all-recursive] Error 1

```

**Comment by glensc** [comment]
can you show full gcc version? (`gcc --version`)

i ran test on travis and with `gcc-6 (Ubuntu 6.2.0-3ubuntu11~12.04) 6.2.0 20160901` it passes:
https://travis-ci.org/glensc/logrotate/jobs/161107138

**Comment by m4ng0squ4sh** [comment]
### gcc version 
```
$ gcc --version
gcc (GCC) 6.2.1 20160830
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### CFLAGS
```
-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong
```


### Buildscript
https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/logrotate

### Current Fix
```
sed 's/^\(AM_CFLAGS = -Wall\) -Werror/\1/' -i Makefile.am
```

**Comment by kdudka** [comment]
@m4ng0squ4sh According to the line numbers in your diagnostic messages, you are building ```logrotate-3.9.2```, which is known to suffer from this bug.  Please try it with ```logrotate-3.10.0```.

**Comment by m4ng0squ4sh** [comment]
Oh, the PKGBUILD got updated lately. Sorry. Thanks for mentioning!

**Comment by kdudka** [comment]
No problem.  Thanks for the clarification!
